sylius_grid:
  grids:
    websnacks_sylius_tag_plugin_tag:
      driver:
        name: doctrine/orm
        options:
          class: '%websnacks_sylius_tag_plugin.model.tag.class%'
      sorting:
        createdAt: desc
      fields:
        name:
          type: string
          label: sylius.ui.name
        enabled:
          type: twig
          label: sylius.ui.enabled
          sortable: ~
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
        createdAt:
          type: datetime
          label: sylius.ui.creation_date
          sortable: ~
          options:
            format: d-m-Y H:i
      actions:
        main:
          create:
            type: create
        item:
          update:
            type: update
          delete:
            type: delete